<?php

$ug = [
    
    'Tab 1' => [
        'course' => 'B.Tech. Artificial Intelligence and Data Science',
        'imgSrc' => '1',
        'id' => 'ugTab1',
        'targetId' => 'ugContentTab1',
        'overview' => 'Artificial Intelligence and Data Science (AI DS) Our 4-year B.Tech program in AI and DS equips students to design intelligent systems, develop ethical and responsible AI solutions, and transform industries. The program emphasizes coding, problem-solving, and real-world applications, preparing students for thriving careers in technology, research, and entrepreneurship. This artificial intelligence course in Pune provides hands-on learning and industry exposure, making it ideal for students seeking practical experience. With a strong focus on practical learning and guaranteed internships, we ensure our students gain industry-relevant experience alongside theoretical knowledge.',
        'eligibility' => '<li>Passed 10+2 examination with Mathematics, Physics, and Chemistry. Obtained at least 45% marks (40% marks in case of candidates belonging to reserved category) in each of the above subjects.</li><li>Passed Minimum THREE years / TWO years (Lateral Entry) Diploma examination with at least 45% marks (40% marks in case of candidates belonging to reserved category) in ANY branch of Engineering and Technology.</li>',
        'specialization' => 'NA',
        'duration' => '4 Years',
    ],

    'Tab 2' => [
        'course' => 'B.Tech. Computer Science Engineering (Artificial Intelligence and Machine Learning)',
        'imgSrc' => '2',
        'id' => 'ugTab2',
        'targetId' => 'ugContentTab2',
        'overview' => 'Artificial Intelligence will be part of our future, it’s inevitable.<br>The department of AI & ML focuses on cutting-edge technologies such as Artificial Intelligence (AI) and Machine Learning (ML). Our department offers comprehensive courses to empower students with knowledge and skills in AI and ML. We emphasize ethics, privacy, and responsible AI practices to ensure the development of socially beneficial AI solutions. Graduates from our department are well-prepared to excel in industry, academia, and entrepreneurship, making a positive impact in the world of AI and ML.<br>The B.Tech in Artificial Intelligence and Machine Learning offered by ALARD University with an intake of 120 seats, is one of the leading artificial intelligence courses in Pune. B.Tech Artificial Intelligence and Machine Learning is a 4 year undergraduate degree program in the engineering stream. In this course, students are taught how to write the code of the said machine. This code works as a guiding instruction for machines so that machines can perform tasks with less human interaction. The UG program’s objective is to create exceptionally well AI and ML engineers who will transform the world through creative AI and ML solutions.',
        'eligibility' => '<li>Passed 10+2 examination with Mathematics, Physics, and Chemistry. Obtained at least 45% marks (40% marks in case of candidates belonging to reserved category) in each of the above subjects.</li><li>Passed Minimum THREE years / TWO years (Lateral Entry) Diploma examination with at least 45% marks (40% marks in case of candidates belonging to reserved category) in ANY branch of Engineering and Technology.</li>',
        'specialization' => 'NA',
        'duration' => '4 Years',
    ],

    'Tab 3' => [
        'course' => 'B.Tech. Computer Science Engineering (Full Stack Developer)',
        'imgSrc' => '3',
        'id' => 'ugTab3',
        'targetId' => 'ugContentTab3',
        'overview' => 'The B.Tech. CSE (Full Stack Developer) program at Alard University, Pune is designed to meet the evolving demands of the global technology industry. Recognized as a growing destination for engineering education in Maharashtra, Alard University blends strong academic foundations with hands-on, industry-aligned learning.
The program offers in-depth training in full stack development, computer science fundamentals, web technologies, cloud computing, databases, and DevOps basics. Students gain practical exposure through modern labs, real-time projects, internships, and expert mentorship—preparing them for careers in today’s competitive tech ecosystem.',
        'eligibility' => '<h6>Eligibility for First Year</h6> <li>   Maharashtra State Candidature Candidates, All India Candidature Candidates, Union Territory of Jammu and Kashmir and Union Territory of Ladakh Migrant Candidature Candidates. </li> <li>   The candidate must be a citizen of India. </li> <li>   The candidate should have passed the 10+2 examination or its equivalent with <strong>Physics and Mathematics</strong> as compulsory subjects along with any one of the following:   Chemistry / Biotechnology / Biology / Technical Vocational Subject / Computer Science / Information Technology / Informatics Practices / Agriculture / Engineering Graphics / BusinessStudies / Electronics / Entrepreneurship, and obtained at least <strong>45% marks</strong> (at least <strong>40%</strong> marks in case of Reserved Categories, Economically Weaker Sectionand Persons with Disability candidates belonging to Maharashtra State only) in the above subjects taken together. </li> <li>   The candidate should have appeared in all subjects of <strong>PCM MHT-CET</strong> and obtained a <strong>non-zero score</strong> in PCM MHT-CET / JEE or examination conducted by theCompetent Authority.     (Such candidates are eligible to apply for all 29 major disciplines declared by AICTE.) </li> <li>   OR the candidate should have passed the 10+2 examination or its equivalent with <strong>Physics and Chemistry</strong> as compulsory subjects along with Mathematics / Biotechnology /Biology / Technical Vocational Subject / Computer Science / Information Technology / Informatics Practices / Agriculture / Engineering Graphics / Business Studies / Electronics /Entrepreneurship as one of the subjects, and obtained at least <strong>45% marks</strong> (at least <strong>40%</strong> marks in case of Reserved Categories, Economically Weaker Sectionand Persons with Disability candidates belonging to Maharashtra State only) in the above subjects taken together. </li> <li>   Such candidates must have appeared in <strong>MHT-CET / JEE</strong> and obtained a <strong>non-zero score</strong> in <strong>Physics, Chemistry and Biology (PCB)</strong> MHT-CET orexamination conducted by the Competent Authority, and are eligible for admission to courses under major disciplines declared by AICTE or the concerned Appropriate Authority, namely:   <ul>     <li>Agriculture Engineering</li>     <li>Biotechnology</li>     <li>Food Engineering</li>     <li>Leather Technology</li>     <li>Packaging Technology</li>     <li>Pharmaceutical Engineering</li>     <li>Printing Engineering</li>     <li>Fashion Technology</li>     <li>Textile Chemistry</li>   </ul> </li> <li>   The candidate should have passed a minimum of <strong>three years Diploma in Engineering and Technology</strong> with at least <strong>45% marks</strong> (at least <strong>40%</strong>marks in case of Reserved Categories, Economically Weaker Section and Persons with Disability candidates belonging to Maharashtra State only). </li> <li>   OR the candidate should have passed a <strong>three years Diploma of Vocation (D.Voc.)</strong> stream in the same or allied sector. </li> <li>   Any other eligibility conditions and requirements as declared from time to time by the appropriate authority under the Act shall be applicable. </li> <br><br> <h6>Eligibility for Lateral Entry – Second Year</h6><ul>  <li>    Applicable for <strong>Maharashtra State Candidature Candidates</strong> and <strong>All India Candidature      Candidates</strong>.  </li>  <li>    The candidate must be a <strong>citizen of India</strong>.  </li>  <li>    The candidate should have passed a minimum of <strong>three years or two years (Lateral Entry) Diploma Course in      Engineering and Technology</strong> with at least <strong>45% marks</strong> (at least <strong>40% marks</strong>    in case of Reserved Categories, Economically Weaker Section and Persons with Disability candidates belonging to    Maharashtra State) in any branch of Engineering and Technology from an institution approved by <strong>AICTE /      Central Government / State Government</strong> or its equivalent.  </li>  <li>    OR the candidate should have passed a <strong>B.Sc. Degree</strong> from a <strong>UGC or Association of Indian      Universities recognized University</strong> with at least <strong>45% marks</strong> (at least <strong>40%      marks</strong> in case of Reserved Categories, Economically Weaker Section and Persons with Disability candidates    belonging to Maharashtra State) and should have passed <strong>HSC or its equivalent examination with Mathematics as      a subject</strong>.  </li>  <li>    OR the candidate should have passed a <strong>three years Diploma of Vocation (D.Voc.)</strong> stream in the same    or allied sector.  </li>  <li>    Any other eligibility criteria and requirements as declared from time to time by the <strong>appropriate      authority</strong> as defined under the Act shall be applicable.  </li></ul>',
        'specialization' => 'NA',
        'duration' => '4 Years',
    ],

    'Tab 4' => [
        'course' => 'B.Tech. Computer Science and Engineering ',
        'imgSrc' => '4',
        'id' => 'ugTab4',
        'targetId' => 'ugContentTab4',
        'overview' => 'The B Tech in Computer Science and Engineering program offered by Alard University, one of the top BTech college in Pune, is one of the best four-year full-time courses for quality education and overall growth of the students. The program emphasises on applying mathematics and principles of computing to solve engineering problems. CSE graduates cater to the needs of most industries, including software, healthcare, communications, manufacturing, automobile to name a few. This program has been designed taking into consideration the views of various academicians and industry experts.',
        'eligibility' => '<li>Passed 10+2 examination with Mathematics, Physics, and Chemistry. Obtained at least 45% marks (40% marks in case of candidates belonging to reserved category) in each of the above subjects.</li><li>Passed Minimum THREE years / TWO years (Lateral Entry) Diploma examination with at least 45% marks (40% marks in case of candidates belonging to reserved category) in ANY branch of Engineering and Technology.</li>',
        'specialization' => 'NA',
        'duration' => '4 Years',
    ],
    'Tab 5' => [
        'course' => 'B.Tech. Computer Science Engineering (Cyber Security and Forensics)',
        'imgSrc' => '5',
        'id' => 'ugTab5',
        'targetId' => 'ugContentTab5',
        'overview' => 'The B Tech in Computer Science and Engineering program offered by Alard University, one of the top BTech college in Pune, is one of the best four-year full-time courses for quality education and overall growth of the students. The program emphasises on applying mathematics and principles of computing to solve engineering problems. CSE graduates cater to the needs of most industries, including software, healthcare, communications, manufacturing, automobile to name a few. This program has been designed taking into consideration the views of various academicians and industry experts.',
        'eligibility' => '<li>Passed 10+2 examination with Mathematics, Physics, and Chemistry. Obtained at least 45% marks (40% marks in case of candidates belonging to reserved category) in each of the above subjects.</li><li>Passed Minimum THREE years / TWO years (Lateral Entry) Diploma examination with at least 45% marks (40% marks in case of candidates belonging to reserved category) in ANY branch of Engineering and Technology.</li>',
        'specialization' => 'NA',
        'duration' => '4 Years',
    ],

    
    'Tab 6' => [
        'course' => 'B.Tech. Computer Science Engineering (Internet of Things)',
        'imgSrc' => '6',
        'id' => 'ugTab6',
        'targetId' => 'ugContentTab6',
        'overview' => 'The B.Tech. Computer Science Engineering (Internet of Things) program at Alard University, Pune prepares students to build smart, data-driven, and connected solutions for the digital world. Recognized as an emerging choice among engineering universities in Maharashtra, Alard University combines academic excellence with hands-on, industry-focused learning.
The program offers strong foundations in computer science, embedded systems, IoT architecture, sensors, networking, cloud platforms, data analytics, and cybersecurity basics. Students gain practical exposure through advanced IoT labs, real-time projects, industry internships, and innovation-driven learning models.',
        'eligibility' => '<h6>Eligibility for First Year</h6> <li>   Maharashtra State Candidature Candidates, All India Candidature Candidates, Union Territory of Jammu and Kashmir and Union Territory of Ladakh Migrant Candidature Candidates. </li> <li>   The candidate must be a citizen of India. </li> <li>   The candidate should have passed the 10+2 examination or its equivalent with <strong>Physics and Mathematics</strong> as compulsory subjects along with any one of the following:   Chemistry / Biotechnology / Biology / Technical Vocational Subject / Computer Science / Information Technology / Informatics Practices / Agriculture / Engineering Graphics / BusinessStudies / Electronics / Entrepreneurship, and obtained at least <strong>45% marks</strong> (at least <strong>40%</strong> marks in case of Reserved Categories, Economically Weaker Sectionand Persons with Disability candidates belonging to Maharashtra State only) in the above subjects taken together. </li> <li>   The candidate should have appeared in all subjects of <strong>PCM MHT-CET</strong> and obtained a <strong>non-zero score</strong> in PCM MHT-CET / JEE or examination conducted by theCompetent Authority.     (Such candidates are eligible to apply for all 29 major disciplines declared by AICTE.) </li> <li>   OR the candidate should have passed the 10+2 examination or its equivalent with <strong>Physics and Chemistry</strong> as compulsory subjects along with Mathematics / Biotechnology /Biology / Technical Vocational Subject / Computer Science / Information Technology / Informatics Practices / Agriculture / Engineering Graphics / Business Studies / Electronics /Entrepreneurship as one of the subjects, and obtained at least <strong>45% marks</strong> (at least <strong>40%</strong> marks in case of Reserved Categories, Economically Weaker Sectionand Persons with Disability candidates belonging to Maharashtra State only) in the above subjects taken together. </li> <li>   Such candidates must have appeared in <strong>MHT-CET / JEE</strong> and obtained a <strong>non-zero score</strong> in <strong>Physics, Chemistry and Biology (PCB)</strong> MHT-CET orexamination conducted by the Competent Authority, and are eligible for admission to courses under major disciplines declared by AICTE or the concerned Appropriate Authority, namely:   <ul>     <li>Agriculture Engineering</li>     <li>Biotechnology</li>     <li>Food Engineering</li>     <li>Leather Technology</li>     <li>Packaging Technology</li>     <li>Pharmaceutical Engineering</li>     <li>Printing Engineering</li>     <li>Fashion Technology</li>     <li>Textile Chemistry</li>   </ul> </li> <li>   The candidate should have passed a minimum of <strong>three years Diploma in Engineering and Technology</strong> with at least <strong>45% marks</strong> (at least <strong>40%</strong>marks in case of Reserved Categories, Economically Weaker Section and Persons with Disability candidates belonging to Maharashtra State only). </li> <li>   OR the candidate should have passed a <strong>three years Diploma of Vocation (D.Voc.)</strong> stream in the same or allied sector. </li> <li>   Any other eligibility conditions and requirements as declared from time to time by the appropriate authority under the Act shall be applicable. </li> <br><br> <h6>Eligibility for Lateral Entry – Second Year</h6><ul>  <li>    Applicable for <strong>Maharashtra State Candidature Candidates</strong> and <strong>All India Candidature      Candidates</strong>.  </li>  <li>    The candidate must be a <strong>citizen of India</strong>.  </li>  <li>    The candidate should have passed a minimum of <strong>three years or two years (Lateral Entry) Diploma Course in      Engineering and Technology</strong> with at least <strong>45% marks</strong> (at least <strong>40% marks</strong>    in case of Reserved Categories, Economically Weaker Section and Persons with Disability candidates belonging to    Maharashtra State) in any branch of Engineering and Technology from an institution approved by <strong>AICTE /      Central Government / State Government</strong> or its equivalent.  </li>  <li>    OR the candidate should have passed a <strong>B.Sc. Degree</strong> from a <strong>UGC or Association of Indian      Universities recognized University</strong> with at least <strong>45% marks</strong> (at least <strong>40%      marks</strong> in case of Reserved Categories, Economically Weaker Section and Persons with Disability candidates    belonging to Maharashtra State) and should have passed <strong>HSC or its equivalent examination with Mathematics as      a subject</strong>.  </li>  <li>    OR the candidate should have passed a <strong>three years Diploma of Vocation (D.Voc.)</strong> stream in the same    or allied sector.  </li>  <li>    Any other eligibility criteria and requirements as declared from time to time by the <strong>appropriate      authority</strong> as defined under the Act shall be applicable.  </li></ul>',
        'specialization' => 'NA',
        'duration' => '4 Years',
    ],
    
    'Tab 7' => [
        'course' => 'Bachelor of Pharmacy',
        'imgSrc' => '7',
        'id' => 'ugTab7',
        'targetId' => 'ugContentTab7',
        'overview' => 'The B.Pharm program is a four-year undergraduate course that offers an in-depth understanding of pharmaceutical science and technology. The curriculum covers a wide range of subjects such as pharmaceutical chemistry, pharmacognosy, pharmacology, and pharmaceutical analysis. Students also gain hands-on experience through practical sessions, internships, and industrial visits, ensuring they are well-prepared for careers in pharmacy practice, research, or industry.',
        'eligibility' => '<li>Candidates must have graduation with at least 45% aggregate marks (for Open category) and 40% aggregate marks (for Reserved category) with Physics, chemistry, Biology and/or Maths.</li><li>Candidate must have positive score in any of NEET/MHT-CET/ AUSET Entrance Test.</li>',
        'specialization' => 'NA',
        'duration' => '4 Years',
    ],
    
    'Tab 8' => [
        'course' => 'B.A. LLB',
        'imgSrc' => '8',
        'id' => 'ugTab8',
        'targetId' => 'ugContentTab8',
        'overview' => 'The B.A. LL.B. is a five-year integrated undergraduate degree program in law, offered by ALARD School of Law. The course combines the study of arts subjects like history, economics, and politics with law subjects like contracts, torts, and constitutional law.',
        'eligibility' => '<li>Qualifying Examination: 10+2 (Higher Secondary) examination in any stream Minimum Marks: 10+2 (Higher Secondary) pass with minimum 50% marks For OPEN. 10+2 (Higher Secondary) pass with minimum 45% marks For any CAST</li><li>Entrance Examination: Common Law Admission Test (CLAT) ALARD Entrance Exam</li>',
        'specialization' => 'NA',
        'duration' => '5 Years',
    ],
    //  'Tab 9' => [
    //     'course' => 'LLB',
    //     'imgSrc' => '9',
    //     'id' => 'ugTab9',
    //     'targetId' => 'ugContentTab9',
    //     'overview' => 'The 3-year LL.B. (Bachelor of Laws) program is a postgraduate degree in law, offered by various law schools and universities in India. The program aims to equip students with a comprehensive understanding of the legal system, as well as critical thinking, research, and analytical skills. Upon completion, graduates are eligible to practice law in India and pursue careers in judiciary, advocacy, corporate law, and more.',
    //     'eligibility' => '<b>Qualifying Examination:</b><ul>    <li>Graduation (3-year or 4-year degree)</li></ul><b>Minimum Marks:</b><ul>    <li>45% aggregate for Open Category</li><li>40% aggregate for Reserved Category</li></ul><b>Entrance Exam:</b><ul> <li>ALARD Entrance & Scholarship Test (AUSET)</li></ul>',
    //     'specialization' => 'NA',
    //     'duration' => '3 Years',
    // ],

    'Tab 10' => [
        'course' => 'Bachelor of Science in Paramedical Technology (Medical Imaging Technology)',
        'imgSrc' => '10',
        'id' => 'ugTab10',
        'targetId' => 'ugContentTab10',
        'overview' => 'Bachelor of Science in Paramedical Technology (Medical Imaging Technology) is an undergraduate-level program with a course duration of 4 years . During study, the student learns about medical imaging techniques and technologies and basic knowledge of human physiology, pathology, and human anatomy.',
        'eligibility' => '<li>10+2 bio stream with 45% marks</li>',
        'specialization' => 'NA',
        'duration' => '3+1 Years',
    ],

    'Tab 11' => [
        'course' => 'Bachelor of Science in Paramedical Technology (Medical Laboratory Technology)',
        'imgSrc' => '11',
        'id' => 'ugTab11',
        'targetId' => 'ugContentTab11',
        'overview' => 'A Bachelor of Science in Paramedical Technology (Medical Laboratory Technology) (MLT) is a 4 year undergraduate program that trains students in diagnostic testing, laboratory procedures, and medical research. The course covers clinical biochemistry, microbiology, hematology, pathology, and blood banking, equipping students with skills to analyze body fluids, detect diseases, and assist in medical diagnostics.',
        'eligibility' => '<li>10+2 bio stream with 45% marks</li>',
        'specialization' => 'NA',
        'duration' => '3+1 Years',
    ],
    'Tab 12' => [
        'course' => 'Bachelor of Science in Biotechnology / Biochemistry / Microbiology',
        'imgSrc' => '12',
        'id' => 'ugTab12',
        'targetId' => 'ugContentTab12',
        'overview' => 'A B.Sc. in Biotechnology is an undergraduate degree program that blends Biology with technology to address problems related to health, agriculture, and the environment. The course involves use of biological organisms, systems, or processes to develop new products, services, and solutions',
        'eligibility' => '<li>10+2 Bio stream with 45% marks</li>',
        'specialization' => 'NA',
        'duration' => '3+1 Years',
    ],
    'Tab 13' => [
        'course' => 'Bachelor of Business Administration',
        'imgSrc' => '13',
        'id' => 'ugTab13',
        'targetId' => 'ugContentTab13',
        'overview' => 'The BBA program equips students with the skills and knowledge of leadership, entrepreneurship, strategic thinking, research, communication, and ethical conduct, which are essential for success in the business world. Students are exposed to the functioning of the corporate world through industry visits, summer internships, and live projects. The lectures are conducted by industry leaders as well as academic faculty, while guest lectures and seminars provide further learning opportunities. The program also provides strong placement training and support from the career services department, along with training for higher studies through various seminars on career opportunities after graduation.',
        'eligibility' => '<li>Student should have scored a minimum of 45% at 10+2 level from ICSE, CBSE, Any State Board Examination, or equivalent examination from any recognized board in Arts, Science, Commerce, or any other stream (at least 40% for reserved category candidates).</li><li>Candidates are selected on the basis of Merit AND Personal Interview conducted by AUP.</li>',
        'specialization' => '<li>Human Resource Management (HRM) </li>
<li>Finance (FIN)</li>
<li> Marketing Management (MKT)</li>
<li> Logistics & Supply Chain Management (LS)</li>',
        'duration' => '3+1 Years',
    ],
    'Tab 14' => [
        'course' => 'Bachelor of Computer Application',
        'imgSrc' => '14',
        'id' => 'ugTab14',
        'targetId' => 'ugContentTab14',
        'overview' => 'Bachelor of Computer Applications is a 4 year course aligned with National Education Policy (NEP) guidelines, with provision for Integrated MCA program, covers essential topics in computer fundamentals, programming, operating systems, mathematics, ethics, and various specialized areas. BCA program equips the students with essential skills and knowledge required and the rapidly evolving IT industry. BCA curriculum covers a wide range of core and elective subjects providing insights into their significance and how they contribute to students’ overall development. These subjects not only focus on theoretical concepts but also emphasize practical applications to tackle real-world challenges.',
        'eligibility' => '<li>Student should have scored a minimum of 45% at 10+2 level from ICSE, CBSE, Any State Board Examination, or equivalent qualification from any recognized board in Science or Commerce, preferably with Mathematics as a subject (at least 40% for reserved category candidates).</li><li>Candidates are selected on the basis of Merit AND Personal Interview conducted by AUP.</li>',
        'specialization' => 'NA',
        'duration' => '4 Years',
    ]
];


// PG ###########################################################################################################################
$pg = [
    'Tab 1' => [
        'course' => 'Master of Pharmacy (Pharmaceutics)',
        'imgSrc' => '1',
        'id' => 'pgTab1',
        'targetId' => 'pgContentTab1',
        'overview' => 'Our M.Pharm program is a two year postgraduate course designed for students who wish to specialize in specific areas of Pharmaceutics and Quality Assurance Techniques. The curriculum is research-oriented, encouraging innovation and advanced study. The program emphasizes both academic and practical learning, enabling students to contribute to the development of new drugs, therapies, and healthcare solutions.',
        'eligibility' => '<li>Candidates must have B. Pharm with minimum 55 % marks aggregate marks (for Open category) and 50% aggregate marks (for Reserved category) from PCI approved Institute.</li><li>Should have obtained PCI Registration or should obtain the same within 1 month from date of admission.</li><li>Candidate must have positive score in any of this GPAT/ AUSET Entrance Test.</li>',
        'specialization' => 'NA',
        'duration' => '2 Years',
    ],
    'Tab 2' => [
        'course' => 'Master of Pharmacy (Pharma Quality Assurance)',
        'imgSrc' => '2',
        'id' => 'pgTab2',
        'targetId' => 'pgContentTab2',
        'overview' => 'Our M.Pharm program is a two year postgraduate course designed for students who wish to specialize in specific areas of Pharmaceutics and Quality Assurance Techniques. The curriculum is research-oriented, encouraging innovation and advanced study. The program emphasizes both academic and practical learning, enabling students to contribute to the development of new drugs, therapies, and healthcare solutions.',
        'eligibility' => '<li>Candidates must have B. Pharm with minimum 55 % marks aggregate marks (for Open category) and 50% aggregate marks (for Reserved category) from PCI approved Institute.</li><li>Should have obtained PCI Registration or should obtain the same within 1 month from date of admission.</li><li>Candidate must have positive score in any of this GPAT/ AUSET Entrance Test.</li>',
        'specialization' => 'NA',
        'duration' => '2 Years',
    ],
    'Tab 3' => [
        'course' => 'Master of Science (Medical Imaging Technology)',
        'imgSrc' => '3',
        'id' => 'pgTab3',
        'targetId' => 'pgContentTab3',
        'overview' => 'Master of Science (Medical Imaging Technology) is specifically aimed at those pursuing a professional career in Imaging Science technology . It is designed to provide specialized training in the scientific principles of modern imaging science and in the application of these principles in the field of radio diagnosis . It is designed as higher degree course suitable for graduates having experience in the technology of imaging science.',
        'eligibility' => '<li>Candidates must have graduation with at least 45% aggregate marks (for Open category) and 40% aggregate marks (for Reserved category) in commerce or science streams.</li><li>Candidate must have positive score in any of this All India Level Entrance Test/ State Level Entrance Test/National Level Entrance Test/ AUSET Entrance Test.</li>',
        'specialization' => 'NA',
        'duration' => '2 Years',
    ],
    'Tab 4' => [
        'course' => 'Master of Science (Embryology)',
        'imgSrc' => '4',
        'id' => 'pgTab4',
        'targetId' => 'pgContentTab4',
        'overview' => 'The Master of Science (Embryology) program at Alard University, Pune is designed for students aspiring to build specialized careers in reproductive biology, clinical embryology, and assisted reproductive technologies. Recognized as a growing destination for postgraduate science education in Maharashtra, Alard University blends strong academic foundations with hands-on laboratory training. The program provides in-depth knowledge of human embryology, reproductive physiology, IVF techniques, cryopreservation, genetics, and laboratory quality management. Students gain practical exposure through advanced labs, clinical training, research projects, and industry-oriented learning, preparing them for real-world clinical and research environments.',
        'eligibility' => "<li>The candidate must have passed a Bachelor's degree in Biotechnology, Life Sciences, or a related field from a recognized university. Minimum aggregate marks required: 50% (45% for reserved categories, Economically Weaker Section, and Persons with Disability candidates belonging to Maharashtra State).</li> <li>The candidate must have appeared in all subjects and obtained a non-zero score in the relevant entrance examination (CET) conducted by the Competent Authority.</li>",
        'specialization' => 'NA',
        'duration' => '2 Years',
    ],
    'Tab 5' => [
        'course' => 'Master of Science (Medical Lab Technology)',
        'imgSrc' => '5',
        'id' => 'pgTab5',
        'targetId' => 'pgContentTab5',
        'overview' => 'The Master of Science (Medical Lab Technology) at Alard University, Pune is a research- and practice-oriented postgraduate program aimed at advancing expertise in clinical diagnostics and laboratory sciences. The program emphasizes analytical excellence, clinical relevance, and interdisciplinary problem-solving under expert academic supervision.',
        'eligibility' => "<li>The candidate must have passed a Bachelor's degree in Medical Laboratory Technology or a related field from a recognized university. Minimum aggregate marks required: 50% (45% for reserved categories, Economically Weaker Section, and Persons with Disability candidates belonging to Maharashtra State).</li><li>The candidate must have appeared in all subjects and obtained a non-zero score in the relevant entrance examination (CET) conducted by the Competent Authority.</li>",
        'specialization' => 'NA',
        'duration' => '2 Years',
    ],
    'Tab 6' => [
        'course' => 'Master of Business Administration',
        'imgSrc' => '6',
        'id' => 'pgTab6',
        'targetId' => 'pgContentTab6',
        'overview' => 'The Master of Business Administration (MBA) program is specially designed keeping in mind the current and future needs of the industry. It prepares young, energetic and curious minds to handle the complexities in the ‘technology led’ future. The School of Business Management at ALARD University, often recognized among the top MBA colleges in Pune, is an enabler that catapults people into higher orbits and makes their dreams come true.<br>This is two-year long, full-time program and is fully residential. Students will have to stay in the university hostels for the entire duration. The unique specializations offered during the second year prepare you to meet the emerging needs to the industry. Experienced faculty drawn from various disciplines and geographies will train you in the program. The School of Business incorporates lectures, tutorials, seminars, presentations, intensive workshops, and fieldwork as part of its teaching methods. Students benefit from a flexible credit system that allows them to take advantage of diverse educational offerings and pursue their own academic interests.',
        'eligibility' => '<li>Open Category student should have scored a minimum of 50% aggregate in Graduation in any stream from UGC approved Institution or equivalent (at least 45% marks, in case of reserved category candidate). Positive score in the following National Level Tests conducted by an apex testing body: CAT, MAT, XAT, PERA, MH-CET, CUET & CMAT or AUP Test will be accepted.</li><li>Candidates are selected on the basis of Group Discussion AND Personal Interview conducted by the AUP.</li>',
        'specialization' => '<li>Marketing Management (MKT)</li><li>International Business (IB)</li><li>Banking Financial Services and Insurance(BFSI)</li><li>FinTech(FT)</li><li>Finance(FIN)</li><li>Human Resource Management(HRM)</li><li>Pharmaceutical Management</li><li>Agri Business Management</li>',
        'duration' => '2 Years',
    ],
    'Tab 7' => [
        'course' => 'Master of Computer Application',
        'imgSrc' => '7',
        'id' => 'pgTab7',
        'targetId' => 'pgContentTab7',
        'overview' => 'The MCA program at ASBM is designed to produce industry-ready professionals who are proficient in multiple programming languages, modern computing technologies, and tools for data analytics and artificial intelligence. The program focuses on both the theoretical and practical aspects of IT, ensuring a well-rounded education.',
        'eligibility' => '<li>Open Category student should have scored a minimum of 50% in any graduation degree (e.g.: B.E. / B.Tech./ B.Sc / B.Com. / B. Voc./ BCA etc.,) with Mathematics at 10+2 levels (at least 45% marks, in case of reserved category candidates).</li><li>Positive score in the All India/State level entrance test or National Level entrance/Entrance test conducted by AUP will be accepted.</li><li>Candidates are selected on the basis of merit AND Personal Interview conducted by AUP.</li>',
        'specialization' => 'NA',
        'duration' => '2 Years',
    ],
     'Tab 8' => [
        'course' => 'LLB',
        'imgSrc' => '8',
        'id' => 'pgTab9',
        'targetId' => 'pgContentTab8',
        'overview' => 'The 3-year LL.B. (Bachelor of Laws) program is a postgraduate degree in law, offered by various law schools and universities in India. The program aims to equip students with a comprehensive understanding of the legal system, as well as critical thinking, research, and analytical skills. Upon completion, graduates are eligible to practice law in India and pursue careers in judiciary, advocacy, corporate law, and more.',
        'eligibility' => '<b>Qualifying Examination:</b><ul>    <li>Graduation (3-year or 4-year degree)</li></ul><b>Minimum Marks:</b><ul>    <li>45% aggregate for Open Category</li><li>40% aggregate for Reserved Category</li></ul><b>Entrance Exam:</b><ul> <li>ALARD Entrance & Scholarship Test (AUSET)</li></ul>',
        'specialization' => 'NA',
        'duration' => '3 Years',
    ],
];


// Diploma ###########################################################################################################################
$diploma = [
    'Tab 1' => [
        'course' => 'Diploma in Pharmacy',
        'imgSrc' => '1',
        'id' => 'diplomaTab1',
        'targetId' => 'diplomaContentTab1',
        'overview' => 'This foundational program is designed for students who wish to start their careers in the pharmacy sector. It provides essential knowledge and skills in pharmaceutical sciences, including pharmacology, pharmaceutics, pharmacognosy, social pharmacy and medicinal chemistry. The D.Pharm curriculum equips students with the competencies required to work as pharmacy technicians in hospitals/ health centers, chemists in retail stores or continue their education in higher pharmacy programs.',
        'eligibility' => '<li>Candidates must have passed 10+2 with at least 45% aggregate marks (for Open category) and 40% aggregate marks (for Reserved category) with subjects Physics, chemistry, Biology or Maths.</li><li>Candidate must have positive score in any of this All India Level Entrance Test/ State Level Entrance Test/National Level Entrance Test/ AUSET Entrance Test.</li>',
        'specialization' => 'NA',
        'duration' => '2 Years',
    ],
];

// Doctorate ###########################################################################################################################
$doctorate = [
        'Tab 1' => [
        'course' => 'Mechanical Engineering',
        'imgSrc' => '1',
        'id' => 'doctorateTab1',
        'targetId' => 'doctorateContentTab1',
        'overview' => 'The Ph.D. in Mechanical Engineering at Alard University, Pune is a research-focused doctoral program aimed at advancing innovation, design excellence, and applied engineering research. The program emphasizes original research, industry relevance, and interdisciplinary problem-solving under expert academic supervision.<br><p><b>Key Research Areas</b></p><ul><li>Advanced Manufacturing</li><li>Thermal Engineering</li><li>Fluid Mechanics Design Engineering</li><li>Materials Science</li><li>Robotics & Automation Mechatronics</li><li>Sustainable & Energy Systems</li></ul>',
        'eligibility' => '<li>As per UGC Guidelines</li>',
        'specialization' => 'NA',
        'duration' => 'Min. 3 Years',
    ],
     'Tab 2' => [
        'course' => 'Electronics and Telecommunication Engineering',
        'imgSrc' => '2',
        'id' => 'doctorateTab2',
        'targetId' => 'doctorateContentTab2',
        'overview' => 'The Ph.D. in Electronics and Telecommunication Engineering at Alard University, Pune is a research-focused doctoral program aimed at advancing innovation, system design, and applied research in electronic and communication technologies. The program emphasizes original research, industry relevance, and interdisciplinary problem-solving under expert academic supervision.<br><p><b>Key Research Areas</b></p><ul><li>Wireless Communication</li><li>VLSI</li><li>Signal Processing</li><li>Embedded Systems</li><li>IoT</li><li>Antenna Engineering</li></ul>',
        'eligibility' => '<li>As per UGC Guidelines</li>',
        'specialization' => 'NA',
        'duration' => 'Min. 3 Years',
    ],
    'Tab 3' => [
        'course' => 'Civil Engineering',
        'imgSrc' => '3',
        'id' => 'doctorateTab3',
        'targetId' => 'doctorateContentTab3',
        'overview' => 'The Ph.D. in Civil Engineering at Alard University, Pune is a research-focused doctoral program aimed at advancing innovation in infrastructure, sustainability, and construction technologies. The program emphasizes original research, industry relevance, and interdisciplinary problem-solving under expert academic supervision.<br><p><b>Key Research Areas</b></p><ul><li>Structural Engineering</li><li>Geotechnical Engineering</li><li>Transportation Engineering</li><li>Environmental Engineering</li><li>Construction Management</li></ul>',
        'eligibility' => '<li>As per UGC Guidelines</li>',
        'specialization' => 'NA',
        'duration' => 'Min. 3 Years',
    ],
    
    'Tab 4' => [
        'course' => 'Computer Science Engineering',
        'imgSrc' => '4',
        'id' => 'doctorateTab4',
        'targetId' => 'doctorateContentTab4',
        'overview' => 'The Ph.D. in Computer Science Engineering at Alard University, Pune is a research-focused doctoral program aimed at advancing innovation in computing systems and digital technologies. The program emphasizes original research, industry relevance, and interdisciplinary problem-solving under expert academic supervision.<br><p><b>Key Research Areas</b></p><ul><li>Artificial Intelligence</li><li>Data Science</li><li>Cloud Computing</li><li>Cyber Security</li><li>Software Engineering</li><li>IoT</li></ul>',
        'eligibility' => '<li>As per UGC Guidelines</li>',
        'specialization' => 'NA',
        'duration' => 'Min. 3 Years',
    ],
   'Tab 5' => [
        'course' => 'Law',
        'imgSrc' => '5',
        'id' => 'doctorateTab5',
        'targetId' => 'doctorateContentTab5',
        'overview' => 'The Ph.D. in Law at Alard University, Pune is a research-focused doctoral program aimed at advancing legal scholarship, policy research, and contemporary legal studies. The program emphasizes original research, social relevance, and interdisciplinary problem-solving under expert academic supervision.<br><p><b>Key Research Areas</b></p><ul><li>Constitutional Law</li><li>Corporate Law</li><li>Criminal Law</li><li>Intellectual Property Rights</li><li>International Law</li></ul>',
        'eligibility' => '<li>As per UGC Guidelines</li>',
        'specialization' => 'NA',
        'duration' => 'Min. 3 Years',
    ],
    'Tab 6' => [
        'course' => 'Mathematics',
        'imgSrc' => '6',
        'id' => 'doctorateTab6',
        'targetId' => 'doctorateContentTab6',
        'overview' => 'The Ph.D. in Mathematics at Alard University, Pune is a research-focused doctoral program aimed at advancing theoretical and applied mathematical sciences. The program emphasizes original research, analytical rigor, and interdisciplinary problem-solving under expert academic supervision.<br><p><b>Key Research Areas</b></p><ul><li>Applied Mathematics</li><li>Statistics</li><li>Computational Mathematics</li><li>Operations Research</li><li>Mathematical Modelling</li></ul>',
        'eligibility' => '<li>As per UGC Guidelines</li>',
        'specialization' => 'NA',
        'duration' => 'Min. 3 Years',
    ],

    'Tab 7' => [
        'course' => 'Chemistry',
        'imgSrc' => '7',
        'id' => 'doctorateTab7',
        'targetId' => 'doctorateContentTab7',
        'overview' => 'The Ph.D. in Chemistry at Alard University, Pune is a research-focused doctoral program aimed at advancing chemical sciences and applied research. The program emphasizes original research, industry relevance, and interdisciplinary problem-solving under expert academic supervision.<br><p><b>Key Research Areas</b></p><ul><li>Organic Chemistry</li><li>Inorganic Chemistry</li><li>Physical Chemistry</li><li>Analytical Chemistry</li><li>Green Chemistry</li></ul>',
        'eligibility' => '<li>As per UGC Guidelines</li>',
        'specialization' => 'NA',
        'duration' => 'Min. 3 Years',
    ],
     'Tab 8' => [
        'course' => 'Pharmaceutics',
        'imgSrc' => '8',
        'id' => 'doctorateTab8',
        'targetId' => 'doctorateContentTab8',
        'overview' => 'The Ph.D. in Pharmaceutics at Alard University, Pune is a research-focused doctoral program aimed at advancing pharmaceutical formulation and drug delivery research. The program emphasizes original research, industry relevance, and interdisciplinary problem-solving under expert academic supervision.<br><p><b>Key Research Areas</b></p><ul><li>Drug Delivery Systems</li><li>Nanotechnology</li><li>Biopharmaceutics</li><li>Pharmacokinetics</li><li>Formulation Development</li></ul>',
        'eligibility' => '<li>As per UGC Guidelines</li>',
        'specialization' => 'NA',
        'duration' => 'Min. 3 Years',
    ],
    'Tab 9' => [
        'course' => 'Pharmaceutical Chemistry',
        'imgSrc' => '9',
        'id' => 'doctorateTab9',
        'targetId' => 'doctorateContentTab9',
        'overview' => 'The Ph.D. in Pharmaceutical Chemistry at Alard University, Pune is a research-focused doctoral program aimed at advancing drug discovery and pharmaceutical analysis. The program emphasizes original research, industry relevance, and interdisciplinary problem-solving under expert academic supervision.<br><p><b>Key Research Areas</b></p><ul><li>Medicinal Chemistry</li><li>Drug Design</li><li> Pharmaceutical Analysis</li><li>Synthetic Chemistry</li><li>Quality Control</li></ul>',
        'eligibility' => '<li>As per UGC Guidelines</li>',
        'specialization' => 'NA',
        'duration' => 'Min. 3 Years',
    ],
    'Tab 10' => [
        'course' => 'Business Management (MCA)',
        'imgSrc' => '10',
        'id' => 'doctorateTab10',
        'targetId' => 'doctorateContentTab10',
        'overview' => 'The Ph.D. in Business Management (MCA) at Alard University, Pune is a research-focused doctoral program aimed at advancing research in computing applications and digital business systems. The program emphasizes original research, industry relevance, and interdisciplinary problem-solving under expert academic supervision.<br><p><b>Key Research Areas</b></p><ul><li>Information Systems</li><li>Business Analytics</li><li>ERP</li><li>Data Management</li><li>Digital Transformation</li></ul>',
        'eligibility' => '<li>As per UGC Guidelines</li>',
        'specialization' => 'NA',
        'duration' => 'Min. 3 Years',
    ],

    'Tab 11' => [
        'course' => 'Public Health',
        'imgSrc' => '11',
        'id' => 'doctorateTab11',
        'targetId' => 'doctorateContentTab11',
        'overview' => 'The Ph.D. in Public Health at Alard University, Pune is a research-focused doctoral program aimed at advancing population health and healthcare systems research. The program emphasizes original research, social relevance, and interdisciplinary problem-solving under expert academic supervision.<br><p><b>Key Research Areas</b></p><ul><li>Epidemiology</li><li>Health Policy</li><li>Community Health</li><li>Public Health Management</li><li>Healthcare Analytics</li></ul>',
        'eligibility' => '<li>As per UGC Guidelines</li>',
        'specialization' => 'NA',
        'duration' => 'Min. 3 Years',
    ],
    'Tab 12' => [
        'course' => 'Radiology and Imaging Technology (RIT)',
        'imgSrc' => '12',
        'id' => 'doctorateTab12',
        'targetId' => 'doctorateContentTab12',
        'overview' => 'The Ph.D. in Radiology and Imaging Technology at Alard University, Pune is a research-focused doctoral program aimed at advancing diagnostic imaging and clinical technologies. The program emphasizes original research, clinical relevance, and interdisciplinary problem-solving under expert academic supervision.<br><p><b>Key Research Areas</b></p><ul><li>Medical Imaging</li><li>Radiological Techniques</li><li>Image Processing</li><li>Radiation Safety</li><li>Diagnostic Technology</li></ul>',
        'eligibility' => '<li>As per UGC Guidelines</li>',
        'specialization' => 'NA',
        'duration' => 'Min. 3 Years',
    ],
    'Tab 13' => [
        'course' => 'Biosciences (Biotechnology/ Microbiology/Biochemistry)',
        'imgSrc' => '13',
        'id' => 'doctorateTab13',
        'targetId' => 'doctorateContentTab13',
        'overview' => 'The Ph.D. in Biosciences at Alard University, Pune is a research-focused doctoral program aimed at advancing biological and life science research. The program emphasizes original research, innovation, and interdisciplinary problem-solving under expert academic supervision.<br><p><b>Key Research Areas</b></p><ul><li>Molecular Biology</li><li>Microbiology</li><li>Biochemistry</li><li>Genetic Engineering</li><li>Bioinformatics</li></ul>',
        'eligibility' => '<li>As per UGC Guidelines</li>',
        'specialization' => 'NA',
        'duration' => 'Min. 3 Years',
    ],
    'Tab 14' => [
        'course' => 'Business Management (MBA)',
        'imgSrc' => '14',
        'id' => 'doctorateTab14',
        'targetId' => 'doctorateContentTab14',
        'overview' => 'The Ph.D. in Business Management (MBA) at Alard University, Pune is a research-focused doctoral program aimed at advancing management theory and business research. The program emphasizes original research, industry relevance, and interdisciplinary problem-solving under expert academic supervision.<br><p><b>Key Research Areas</b></p><ul><li>Strategic Management</li><li>Marketing</li><li>Finance</li><li>Human Resource Management</li><li>Entrepreneurship</li><li>Operations</li></ul>',
        'eligibility' => '<li>As per UGC Guidelines</li>',
        'specialization' => 'NA',
        'duration' => 'Min. 3 Years',
    ],
    'Tab 15' => [
        'course' => 'Electrical Engineering',
        'imgSrc' => '15',
        'id' => 'doctorateTab15',
        'targetId' => 'doctorateContentTab15',
        'overview' => 'The Ph.D. in Electrical Engineering at Alard University, Pune is a research-focused doctoral program aimed at advancing electrical systems and energy technologies. The program emphasizes original research, industry relevance, and interdisciplinary problem-solving under expert academic supervision.<br><p><b>Key Research Areas</b></p><ul><li>Power Systems</li><li>Renewable Energy</li><li>Control Systems</li><li>Electrical Machines</li><li>Smart Grids</li></ul>',
        'eligibility' => '<li>As per UGC Guidelines</li>',
        'specialization' => 'NA',
        'duration' => 'Min. 3 Years',
    ],
     'Tab 16' => [
        'course' => 'Artificial Intelligence and Machine Learning Engineering',
        'imgSrc' => '16',
        'id' => 'doctorateTab16',
        'targetId' => 'doctorateContentTab16',
        'overview' => 'The Ph.D. in Artificial Intelligence and Machine Learning Engineering at Alard University, Pune is a research-focused doctoral program aimed at advancing intelligent systems and data-driven technologies. The program emphasizes original research, industry relevance, and interdisciplinary problem-solving under expert academic supervision.<br><p><b>Key Research Areas</b></p><ul><li>Machine Learning</li><li>Deep Learning</li><li>Computer Vision</li><li>Natural Language Processing</li><li>Data Science</li></ul>',
        'eligibility' => '<li>As per UGC Guidelines</li>',
        'specialization' => 'NA',
        'duration' => 'Min. 3 Years',
    ],

    'Tab 17' => [
        'course' => 'Hospital Administration',
        'imgSrc' => '17',
        'id' => 'doctorateTab17',
        'targetId' => 'doctorateContentTab17',
        'overview' => 'The Ph.D. in Hospital Administration at Alard University, Pune is a research-focused doctoral program aimed at advancing healthcare management and hospital systems research. The program emphasizes original research, industry relevance, and interdisciplinary problem-solving under expert academic supervision.<br><p><b>Key Research Areas</b></p><ul><li>Healthcare Operations</li><li>Hospital Planning</li><li>Health Economics</li><li>Quality Management</li><li>Healthcare Policy</li></ul>',
        'eligibility' => '<li>As per UGC Guidelines</li>',
        'specialization' => 'NA',
        'duration' => 'Min. 3 Years',
    ],
];

?>